# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Henri Chevallier
email: ""
description: Blog about development. Anything that interests me at work or at home.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://heshyo.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Henri Chevallier'
bio: >
  Hey there, I'm Henri Chevallier.
  I've been developing professionally since 2004 and for fun on small calculators since around 1995.
  Here is my blog where I write about things I like and encounter at work.
  This also acts as a memory dump/documentation so that if I encounter something that I know I'll forget,
  I just write about it and I won't have to search for it again online.
author_image: "/assets/images/author.jpg"
# twitter_username:
github_username:  heshyo
disqus_shortname: heshyo

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
